### ISSUE TITLE
Really slow startup due to GUI construction

### ISSUE THREAD

**Issue by t3kt** [frauzufall/ofxGuiExtended#48]
I'm encountering a significant amount of time (5+ seconds) spent during startup constructing the UI (from a nested structure of ofParameterGroups). Profiling indicates that a lot of the time is in ofxGuiElement::copyLayoutFromDocument(), more specifically DOM::Element::invalidateChildShape().

Would it be possible to suppress layout activity until after the GUI controls have been added?

```
void AppGui::setup() {
  _gui = std::make_shared<ofxGui>();
  _gui->setupFlexBoxLayout();
  _mainPanel = _gui->addPanel();
  _mainPanel->setBackgroundColor(ofFloatColor(1, 1, 1, 0.5));
  auto rootGroup = _mainPanel->addGroup();

  auto rootTabs = rootGroup->addTabs();
  rootTabs->setWidth(150);
  rootTabs->setTabHeight(6);
  rootTabs->setTabWidth(44);
  auto coreTab = rootTabs->addGroup(_appParams.core);
  {
    auto entityTabs = rootTabs->addTabs("Ent");
    entityTabs->setTabHeight(6);
    entityTabs->setTabWidth(44);
    entityTabs->addGroup(_appParams.observers)->setName("Obs");
    entityTabs->addGroup(_appParams.occurrences)->setName("Occ");
    entityTabs->addGroup(_appParams.navigators)->setName("Nav");
  }
  {
    auto visTabs = rootTabs->addTabs("Vis");
    visTabs->setTabHeight(6);
    visTabs->setTabWidth(44);
    visTabs->addGroup(_appParams.animations)->setName("Ani");
    visTabs->addGroup(_appParams.colors)->setName("Col");
    visTabs->addGroup(_appParams.rendering)->setName("Ren");
  }
  rootTabs->addGroup(_appParams.physics)->setName("Phys");
  rootTabs->addGroup(_appParams.debug)->setName("Dbg");

  loadTheme();
  _mainPanel->setWidth(150);
}

void AppGui::loadTheme() {
  _mainPanel->loadTheme("theme.json");
}
```

see https://github.com/t3kt/memory/blob/3159e41db21d1bed5c13245cc76e021bacce8254/src/app/AppGui.cpp

**Comment by frauzufall** [comment]
Jepp, I have that problem too with some, specifically more complex, layouts. The flexbox implementation is not pretty. I would love to redo it, but it's tricky, I tried quite a few times and I am at my limits there doing this in my free time without anyone to talk it through. But I will definitely try it again since it bugs me too ;)

You can suppress the layout computation with this function:

```
_mainPanel->blockLayout(true);
// ..add stuff to main panel
_mainPanel->blockLayout(false);
```

That improved my loading times quite a bit. Try it and tell me if it helped!

**Comment by frauzufall** [comment]
I also had a look at your code. I sadly can't run it, but I still think I can give you a hint regarding the loading time. 

I get way worse results when I try to add child elements to a group with a fixed size where they don't fit in. For example, your tabs have a width of 44px and there are 5 tabs, but rootTabs is set to150px.  Remove the tab width or don't give the group a width to let it grow to the size of its child elements. (Just remove `_mainPanel->setWidth(150);` and `rootTabs->setWidth(150);`. 

You can also use the flexbox attributes to align and size the elements rather than using absolute pixel values for child elements. The [layout example](https://github.com/frauzufall/ofxGuiExtended/tree/master/exampleLayout) may be helpful, this scenario mixes fixed and flexible sizes. You can use `{"flex", 1}` to stretch an element over the remaining width (or height in a group with `{"flex-direction", "row"}`). You can also use this attribute with multiple elements to divide the remaining space equally between them. I guess I need some illustrations to better document the features of this layout.

**Comment by t3kt** [comment]
Using blockLayout() fixed the issue. Thanks!
