### ISSUE TITLE
any way to make a mouse-clickable image button?

### ISSUE THREAD

**Issue by moebiussurfing** [frauzufall/ofxGuiExtended#74]
I would like to make a grid of (thumb) images using ofxGuiGraphics clickable to load/enable an item...

could this be done in some way?

**Comment by moebiussurfing** [comment]
maybe could create a new control (extending ofxGuiGraphics) like mentioned on the readme?
```
Adding controls
Controls get automatically created whenever you add a parameter to the GUI.
panel->add(moving);    // creates a toggle
...
You can also add a specific control (this is very useful if you implement your own control classes):
panel->add<ofxGuiLabel>("labeltext");
panel->add<yourControlElementClass>(/* contructor parameters of control element class */);
```

Anybody know how to do it?

**Comment by frauzufall** [comment]
Hi @moebiussurfing, sorry I missed a lot of notifications for this repo.. I'll try to take a day off soon where I will look into some open issues. Impossible to make any promises though. Sorry.

**Comment by frauzufall** [comment]
There are now two new options for any element: `background-image` and `background-size`. With the first you specify the path to an image (relative to `bin` or absolute should work), and `background-size` can be either `scale`, `cover`, or `contain`. I added their descriptions to the README. The different sizings are demonstrated [here](https://github.com/frauzufall/ofxGuiExtended/tree/master/exampleAdvancedGui). There are also methods to set them not by JSON but via API, I did not test them though.. But the API allows you to set the background image to an `ofTexture` element, which might be what you would prefer to file paths.

Since you can't directly set the size for a button currently, use the `padding` to adjust it, see example.

Let me know if you run into any issues!

**Comment by moebiussurfing** [comment]
thanks @frauzufall !

**Comment by moebiussurfing** [comment]
I pulled into my fork and it worked perfectly. thanks again.
